prosecution_task:
  description: >
    Prepare and present the prosecution's argument based on the given case details.
    Ensure that legal precedents, evidence, and logical reasoning support the charges.
    Cross-examine responses and counter any defense arguments effectively.
  expected_output: >
    A structured argument outlining the prosecution's case with legal references,
    key evidence, and counterarguments. Formatted as markdown without '```'.
  agent: prosecutor

judgment_task:
  description: >
    Evaluate the arguments presented by the prosecution and the defense.
    Ask clarifying questions where needed and ensure that legal principles
    are correctly applied. Deliver an impartial verdict with reasoning.
  expected_output: >
    A judgment summary detailing the legal analysis, case evaluation, and final ruling.
    Formatted as markdown without '```'.
  agent: judge

review_task:
  description: >
    Analyze and assess the law student's performance in presenting arguments.
    Provide constructive feedback on legal reasoning, argument structure, 
    and presentation skills. Suggest case law references and improvements.
  expected_output: >
    A detailed feedback report with strengths, weaknesses, and actionable insights
    to improve the student's advocacy skills. Formatted as markdown without '```'.
  agent: reviewer
